# Generated by Django 4.2.4 on 2023-09-23 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("farm_one", "0003_farmone_updated_at_farmonesubject_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmone",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="farmonesubject",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="updated_at",
        ),
    ]
